version: '3.9'

services:
  tgbot:
    restart: always
    build: .
    command: python main.py
    container_name: bot
    volumes:
      - /root/01_bot_books_shop/database.db:/tg_bot/database.db
    env_file:
      - ".env"